Circle_Using_Square.py
This is a basic python program for issue #1
=> Circle using number of squares

masking(opencv).py
added a new python program built using opencv2 and numpy libraries in python
=> added a python program built using opencv

electricity_consumption.py
Calculates electricity consumed
=> Added a python program for power billing.

Random Walk.py
=> added Random Walk

snake.py
Fixes #7 
Add a simple snake game (snake.py)
=> Add a simple snake game

search_commits.py
Inspired by a random bot of Instagram
=> Added a program that returns commits that contain specific words

singly_linked_list.py
Signed-off-by: Vigneshwar Ravichandran <vigneshwarravichandran@gmail.com>
Added Singly Linked List
=> Singly Linked List

portscanner.py
This small port scanner program will try to connect on every port you define for
a particular host. The first thing we must do is import the socket library and other libraries that
we need.
=> port scanner in python

sort_n_numbers.py
=> added a program to sort n numbers

README.md, chess.py
=> Chess game

igdata.py
Scrapes data from public instagram profile and posts and saves it into json file.
=> Instagram Scraper

SimpleCalculator.py
Making a simple calculator which can perform operations like addition, subtraction, multiplication and division.
=> Calculator

palindrome.py
Python code to check if the input string is a palindrome.
=> Palindrome

README.md, markov/main.py, markov/sample/christmascarol.txt
Added an implementation of a Markov Chain in Python3.
The Markov Chain is an algorithm that analyses large bodies of text to identify patterns in how words proceed each other. New sentences can then be generated in a similar style to the training data by selecting an initial word and generating further text from what most commonly follows the preceding term.
Similar technology is used in messaging applications to autocomplete sentences or suggest a term that the user is statistically likely to use, given their current input.
`markov/main.py` contains the implementation, whilst `markov/sample/christmascarol.txt` contains the complete text of Charles Dickens' "A Christmas Carol", used to generate example data.
=> Hacktoberfest: Markov Chain

result_checker.py
This program checks for result and notifies on Ubuntu desktop only, for now.
=> Result Checker

linked_list.py
Singly linked list implementation in python
=> Singly linked list insertion and display

gcd.py, lcm.py
Hi. 
I added a small program that calculates the greatest common divisor and least common multiple.
thanks.
=> add small python script: calculate gcd and lcm

number_system_convertor.py
a application which convert the number 
in a desired system.
=> number_system_convertor.py

keylogger/keylogger.py
please add __name__ variable. So, you can use this script as a module without any bug.
=> add __name__ variable

regular_expressions
A simple program to get started with regular expressions
=> regular_expressions.py
